name: server
on: workflow_dispatch
jobs:
  server:
    runs-on: macos-latest
    steps:
      - run: |
          brew install openssl@3
          /opt/homebrew/opt/openssl@3/bin/openssl speed -multi 3 -evp aes-128-gcm
