name: server
on: workflow_dispatch
jobs:
  server:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          sudo apt-get install hping3
          curl -s http://ip-api.com/line/
          sudo hping3 -S -p 443 -c 4 87.226.162.216
