name: server
on: workflow_dispatch
jobs:
  server:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/location?api-version=2021-02-01&format=text"
      - run: |
          docker run -d --name=webtop --privileged --shm-size="1gb" --network=host -e PUID=1000 -e PGID=1000 -e TZ=Europe/Moscow -e CUSTOM_USER=admin -e PASSWORD=qwerty -v webtop_data:/config --restart unless-stopped lscr.io/linuxserver/webtop:debian-xfce
          wget -qO cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64 && chmod +x cloudflared && ./cloudflared tunnel --url http://localhost:3000
